### ISSUE TITLE
cannot get html templates to update

### ISSUE THREAD

**Issue by rednaxus** [markmarijnissen/cordova-app-loader#22] opened 2015-02-26 03:51 UTC
works great for .js and .css, but the old .html stays cached for some reason, I'm sure the files are getting there.  I try clearing the template cache, but that doesn't seem to help.

**Comment by Urbiwanus** [comment] 2015-02-27 08:47
i found a solution for angularjs check 
http://forum.ionicframework.com/t/cordova-app-loader/16090/29

**Comment by Urbiwanus** [comment] 2015-03-01 21:25
After some research i think there is no easy way to to guaranty that the html is always the latest one. Since the current bootstrap.js includes every file (except js) as css link. This works sometimes if the browser cache serves the included file instead of the file includes in your app. 

A solution for this problem would be a native plugin, which hooks into the file://... calls done by your app. 

For Android i think this can be done with http://developer.android.com/reference/android/webkit/WebViewClient.html#shouldOverrideUrlLoading(android.webkit.WebView, java.lang.String)

IOS 
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIWebViewDelegate/webView:shouldStartLoadWithRequest:navigationType:

But this is just an idea.

**Comment by markmarijnissen** [comment] 2015-03-04 07:57
Hey! 

I am not sure I fully understand you, but let me say one thing first:

**Bootstrap.js** is **NOT** meant as access point for all your files. Use `loader.cache.get(...)` for this. The **only purpose** of bootstrap.js is to, uhm, bootstrap a Single Page Application (SPA). SPA have by definition only one html file. All other HTML and templates are generated by Javascript. They are either included in the Javascript, or downloaded using a XHR request. 

In order to provide maximum flexibility in the app loader, you're allowed to configure the JS and CSS files that are loaded in your SPA. (Changing `index.html` itself will cause problems loading the Cordova plugin, see README).

So, in conclusion: 

* Bootstrap loads **by design** only CSS and JS. It will never load HTML or other filetypes. 
* To access other files, use `loader.cache.get(...)`.
* Angular assumes that your template URLS are relative to the `index.html`, whereas they should be relative to the local cache root. Best way to deal with this is to write a HTTP interceptor (as you did). You can always append a querystring (such as the current time) to by-pass the browser cache.

Questions for you:
* Reading this, do you agree we don't need `file://` support in Bootstrap.js? If not, what am I missing?
* Does adding a timestamp querystring to your HTTP interceptor solve your cache problems?
* Is there anything else you asked that I have missed?

**Comment by Urbiwanus** [comment] 2015-03-04 08:30
Hi and thank you very much for the detail answer. 

No you didn´t  missed anything. 
Working with an HTTP Interceptor solves the issue for html and image files. ( See mentioned forum post )

file:// url is more a generic problem and I think its not necessary to solve this until a real world issues appears . 

## Some thoughts
Since there is no standard no plugin/code for cordova apps to manage updates easily ( and of course to bypass the f**king app store approvals ). 

Your solution seems to be one of best ( easy to use, works well ( after a tiny learning curve and minor bugfixes ) , self hosting , simple to integrate into a build flow ). 

But as you mentioned it has some limitations ( only css/js files ). But whats really wanted is a system which manage all files mentioned in the manifest, without do deal with it in the app itself. 

Thats why i came up with the idea of native plugins. 

It would be great the extend the cordova app loader to a full app loader which deals with all kind of files 
For xhr see http://verboselogging.com/2010/02/20/hijack-ajax-requests-like-a-terrorist

**Comment by ObjectiveTruth** [comment] 2015-08-29 13:17
If you're using Angular or Ionic by extension, I **HIGHLY** recommend using `$templateCache`. It turns all your html template files into a nice .js file you can add to your manifest. Almost no change required if you're calling templates by filename.

Not only does it make your cordova/ionic app wayy faster, it also allows you to update using `cordova-app-loader`

Here's the gulp task I use [gulp-angular-templatecache](https://www.npmjs.com/package/gulp-angular-templatecache)

**Comment by ObjectiveTruth** [comment] 2015-09-13 00:11
Closing issue since it appears to be answered adequately, if there is more information, please reopen :ok_hand:

**Closed by ObjectiveTruth** 2015-09-13 00:11 UTC
Labels: question, wontfix

**Comment by NicksonYap** [comment] 2016-05-01 15:11
Hello, I am using Ionic framework + cordova-app-loader plugin.
I was using Ionic's Deploy service until I realise it will be a paid service once they update away from beta.

I find that this is an important note for those using Angular.
Probably add this explanation to docs?
